spring.application.name=projetoIntegradorI.GestaoDeCondominio
# application.properties with correct encoding (UTF-8)

# Configuração do banco de dados H2
spring.datasource.url=jdbc:h2:file:C:/Users/Nathalia/test;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do H2 para visualização dos dados
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualiza o banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update
# Isto deve ser usado no Hibernate 6+

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8